module.exports.branch = {
    "Btech-CSE":"CSE",
    "Btech-IT":"IT",
    "Btech-ECE":"ECE",
    "Btech-CE":"CE",
    "Btech-ME":"ME",
    "BE-CSE":"CSE",
    "BE-IT":"IT",
    "BE-ECE":"ECE",
    "BE-CE":"CE",
    "BE-ME":"ME",
    "MCA":"MCA",
    "M.E. Structural Engineering":"MCE",
    "M.Tech Computer Science & Engineering":"MCS",
    "M.Tech Digital Communication":"MEC",
    "M.Tech Thermal System & Design":"MME",
    "MBA":"MBA",
};